[window]
padding = { x = 0, y = 5}
opacity = 0.75

[font.normal]
family = "JetBrainsMono Nerd Font"

[font]
size = 11.0

[scrolling]
multiplier = 5

[colors.primary]
background = "#0f0a14"
foreground = "#eff0eb"

[colors.cursor]
cursor = "#97979b"

[colors.selection]
text = "#282a36"
background = "#feffff"

[colors.normal]
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"

[colors.bright]
black = "#686868"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#eff0eb"